[server]
port = 8501
runOnSave = true

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(filename)s:%(lineno)d:%(funcName)s %(message)s"

[theme]
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"